import express from 'express';
import rateLimit from 'express-rate-limit';
import helmet from 'helmet';
import multer from 'multer';
import bcrypt from 'bcryptjs';
import nodemailer from 'nodemailer';
import crypto from 'node:crypto';
import { OAuth2Client } from 'google-auth-library';
import { getDatabase } from '@netlify/database';
import { getStore } from '@netlify/blobs';
import serverless from 'serverless-http';

const app = express();
const db = getDatabase();
const blobs = getStore('yovies-uploads');
const SECRET = process.env.SESSION_SECRET || 'CHANGE_ME_YOVIES_SESSION_SECRET';
const COOKIE = 'yovies_session';
const ADMIN_COOKIE = 'yovies_admin';
const DAY = 86400000;

app.use(helmet({ crossOriginOpenerPolicy:false, contentSecurityPolicy:false }));
app.use(express.json({ limit:'2mb' }));
app.use(express.urlencoded({ extended:true }));
app.use('/api/', rateLimit({ windowMs:15*60*1000, max:300, standardHeaders:true, legacyHeaders:false }));
const otpLimiter = rateLimit({ windowMs:10*60*1000, max:5, standardHeaders:true, legacyHeaders:false, message:{error:'Bạn gửi mã quá nhiều. Hãy thử lại sau.'} });
const upload = multer({ storage:multer.memoryStorage(), limits:{ fileSize:4*1024*1024 } });

function b64(v){ return Buffer.from(v).toString('base64url'); }
function unb64(v){ return Buffer.from(v,'base64url').toString(); }
function sign(payload){ const body=b64(JSON.stringify(payload)); const sig=crypto.createHmac('sha256',SECRET).update(body).digest('base64url'); return body+'.'+sig; }
function verify(token){ try { const [body,sig]=String(token||'').split('.'); if(!body||!sig)return null; const good=crypto.timingSafeEqual(Buffer.from(sig),Buffer.from(crypto.createHmac('sha256',SECRET).update(body).digest('base64url'))); if(!good)return null; const p=JSON.parse(unb64(body)); return p.exp>Date.now()?p:null; } catch { return null; } }
function setCookie(res,name,value){ res.setHeader('Set-Cookie',`${name}=${value}; Path=/; HttpOnly; SameSite=Lax; Secure; Max-Age=${7*86400}`); }
function clearCookie(res,name){ res.setHeader('Set-Cookie',`${name}=; Path=/; HttpOnly; SameSite=Lax; Secure; Max-Age=0`); }
function auth(req,res,next){ const p=verify(req.headers.cookie?.match(new RegExp('(?:^|; )'+COOKIE+'=([^;]+)'))?.[1]); if(!p||p.kind!=='user')return res.status(401).json({error:'UNAUTHORIZED'}); req.userId=p.id; next(); }
function admin(req,res,next){ const p=verify(req.headers.cookie?.match(new RegExp('(?:^|; )'+ADMIN_COOKIE+'=([^;]+)'))?.[1]); if(!p||p.kind!=='admin')return res.status(401).json({error:'ADMIN_UNAUTHORIZED'}); req.adminId=p.id; next(); }
function clean(u){ return u&&{id:Number(u.id),username:u.username,email:u.email,balance:Number(u.balance),invite:u.invite}; }
function emailOk(e){ return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(e); }
function code(){ return String(crypto.randomInt(100000,1000000)); }
function invite(){ return 'YOVIES-'+crypto.randomBytes(4).toString('hex').toUpperCase(); }
function mailer(){ if(!process.env.SMTP_HOST||!process.env.SMTP_USER||!process.env.SMTP_PASS)return null; return nodemailer.createTransport({host:process.env.SMTP_HOST,port:Number(process.env.SMTP_PORT||465),secure:String(process.env.SMTP_SECURE||'true')==='true',auth:{user:process.env.SMTP_USER,pass:process.env.SMTP_PASS}}); }
async function otpSend(email,purpose,subject){ const tx=mailer(); if(!tx)throw Object.assign(new Error('SMTP_NOT_CONFIGURED'),{status:503}); const c=code(); await db.sql`UPDATE otp_codes SET used=true WHERE email=${email} AND purpose=${purpose} AND used=false`; await db.sql`INSERT INTO otp_codes(email,code_hash,purpose,expires_at) VALUES(${email},${bcrypt.hashSync(c,10)},${purpose},${Date.now()+10*60*1000})`; await tx.sendMail({from:process.env.SMTP_FROM||process.env.SMTP_USER,to:email,subject,text:`Mã YOVIES CINEMAS của bạn là: ${c}. Mã hết hạn sau 10 phút.`,html:`<div style="font-family:Arial;background:#0b0b0e;color:#fff;padding:28px;border-radius:16px"><h2 style="color:#d8b85a">YOVIES CINEMAS</h2><p>${subject}</p><div style="font-size:34px;font-weight:800;letter-spacing:8px">${c}</div><p style="color:#aaa">Mã có hiệu lực trong 10 phút.</p></div>`}); }
async function latestOtp(email,purpose,otp){ const r=await db.sql`SELECT * FROM otp_codes WHERE email=${email} AND purpose=${purpose} AND used=false ORDER BY id DESC LIMIT 1`; const x=r[0]; return x && Number(x.expires_at)>=Date.now() && bcrypt.compareSync(String(otp),x.code_hash)?x:null; }

app.get('/api/config',(req,res)=>res.json({googleClientId:process.env.GOOGLE_CLIENT_ID||''}));
app.get('/api/me',async(req,res)=>{ const p=verify(req.headers.cookie?.match(new RegExp('(?:^|; )'+COOKIE+'=([^;]+)'))?.[1]); if(!p||p.kind!=='user')return res.json({user:null}); const r=await db.sql`SELECT * FROM users WHERE id=${p.id}`; res.json({user:clean(r[0])}); });
app.get('/api/movies',async(req,res)=>{ const rows=await db.sql`SELECT id,title,genre,duration,price,poster,video FROM movies ORDER BY id`; res.json({movies:rows.map(x=>({...x,id:Number(x.id),price:Number(x.price)}))}); });

app.post('/api/auth/request-otp',otpLimiter,async(req,res)=>{ try{ const email=String(req.body.email||'').trim().toLowerCase(); if(!emailOk(email))return res.status(400).json({error:'Email không hợp lệ'}); const u=await db.sql`SELECT id FROM users WHERE email=${email}`; if(u.length)return res.status(409).json({error:'Email đã được đăng ký'}); await otpSend(email,'register','Mã xác minh đăng ký Gmail:'); res.json({ok:true}); }catch(e){res.status(e.status||500).json({error:e.status===503?'Máy chủ chưa cấu hình SMTP để gửi mã Gmail':'Không gửi được email xác minh. Kiểm tra SMTP.'});} });
app.post('/api/auth/request-reset-otp',otpLimiter,async(req,res)=>{ try{ const email=String(req.body.email||'').trim().toLowerCase(); if(!emailOk(email))return res.status(400).json({error:'Email không hợp lệ'}); const u=await db.sql`SELECT id FROM users WHERE email=${email}`; if(u.length)await otpSend(email,'reset','Mã đặt lại mật khẩu:'); res.json({ok:true}); }catch(e){res.status(e.status||500).json({error:e.status===503?'Máy chủ chưa cấu hình SMTP để gửi mã Gmail':'Không gửi được email. Kiểm tra SMTP.'});} });

app.post('/api/register',async(req,res)=>{ const username=String(req.body.username||'').trim(),email=String(req.body.email||'').trim().toLowerCase(),password=String(req.body.password||''),inviteCode=String(req.body.invite||'').trim().toUpperCase(),otp=String(req.body.otp||''); if(username.length<2||!emailOk(email)||password.length<6||!/^[0-9]{6}$/.test(otp))return res.status(400).json({error:'Thông tin đăng ký không hợp lệ'}); const exists=await db.sql`SELECT id FROM users WHERE email=${email}`; if(exists.length)return res.status(409).json({error:'Email đã được đăng ký'}); const o=await latestOtp(email,'register',otp); if(!o)return res.status(400).json({error:'Mã xác minh Gmail không đúng hoặc đã hết hạn'}); const client=await db.pool.connect(); try{await client.query('BEGIN'); let inviter=null; if(inviteCode){ const ir=await client.query('SELECT * FROM invite_codes WHERE code=$1 FOR UPDATE',[inviteCode]); if(!ir.rows[0]||ir.rows[0].used_by)throw Object.assign(new Error('INVITE_INVALID'),{status:400}); inviter=ir.rows[0]; } const inv=invite(); const hash=bcrypt.hashSync(password,12); const u=await client.query('INSERT INTO users(username,email,password_hash,invite,invited_by,balance) VALUES($1,$2,$3,$4,$5,100) RETURNING *',[username,email,hash,inv,inviter?.user_id||null]); await client.query('INSERT INTO invite_codes(code,user_id) VALUES($1,$2)',[inv,u.rows[0].id]); if(inviter){ await client.query('UPDATE invite_codes SET used_by=$1,used_at=NOW() WHERE code=$2',[u.rows[0].id,inviteCode]); await client.query('UPDATE users SET balance=balance+15 WHERE id=$1',[inviter.user_id]); await client.query('INSERT INTO transactions(user_id,amount,type,ref) VALUES($1,15,$2,$3)',[inviter.user_id,'invite',inviteCode]); await client.query('UPDATE users SET balance=balance+10 WHERE id=$1',[u.rows[0].id]); await client.query('INSERT INTO transactions(user_id,amount,type,ref) VALUES($1,10,$2,$3)',[u.rows[0].id,'invite',inviteCode]); } await client.query('UPDATE otp_codes SET used=true WHERE id=$1',[o.id]); await client.query('COMMIT'); setCookie(res,COOKIE,sign({kind:'user',id:u.rows[0].id,exp:Date.now()+7*DAY})); res.json({user:clean(u.rows[0])}); }catch(e){await client.query('ROLLBACK');res.status(e.status||500).json({error:e.message==='INVITE_INVALID'?'Mã mời không hợp lệ hoặc đã được sử dụng':'Không thể tạo tài khoản'});}finally{client.release();} });

app.post('/api/login',async(req,res)=>{ const email=String(req.body.email||'').trim().toLowerCase(),password=String(req.body.password||''); const r=await db.sql`SELECT * FROM users WHERE email=${email}`; if(!r[0]||!r[0].password_hash||!bcrypt.compareSync(password,r[0].password_hash))return res.status(401).json({error:'Email hoặc mật khẩu không đúng'}); setCookie(res,COOKIE,sign({kind:'user',id:r[0].id,exp:Date.now()+7*DAY})); res.json({user:clean(r[0])}); });
app.post('/api/auth/reset-password',async(req,res)=>{ const email=String(req.body.email||'').trim().toLowerCase(),otp=String(req.body.otp||''),password=String(req.body.password||''); const u=(await db.sql`SELECT * FROM users WHERE email=${email}`)[0],o=await latestOtp(email,'reset',otp); if(!u||!o||password.length<6)return res.status(400).json({error:'Mã xác minh hoặc mật khẩu không hợp lệ'}); await db.sql`UPDATE users SET password_hash=${bcrypt.hashSync(password,12)} WHERE id=${u.id}`; await db.sql`UPDATE otp_codes SET used=true WHERE id=${o.id}`; clearCookie(res,COOKIE); res.json({ok:true}); });
app.post('/api/auth/google',async(req,res)=>{try{if(!process.env.GOOGLE_CLIENT_ID)return res.status(503).json({error:'Chưa cấu hình GOOGLE_CLIENT_ID'});const c=new OAuth2Client(process.env.GOOGLE_CLIENT_ID);const t=await c.verifyIdToken({idToken:req.body.credential,audience:process.env.GOOGLE_CLIENT_ID});const p=t.getPayload(),email=String(p.email||'').toLowerCase();if(!email||p.email_verified===false)throw Error('unverified');let u=(await db.sql`SELECT * FROM users WHERE email=${email}`)[0];if(!u){const inv=invite();const r=await db.sql`INSERT INTO users(username,email,google_sub,invite,balance) VALUES(${p.name||p.given_name||'Google User'},${email},${p.sub},${inv},100) RETURNING *`;u=r[0];await db.sql`INSERT INTO invite_codes(code,user_id) VALUES(${inv},${u.id})`;}else if(!u.google_sub){await db.sql`UPDATE users SET google_sub=${p.sub} WHERE id=${u.id}`;u=(await db.sql`SELECT * FROM users WHERE id=${u.id}`)[0];}setCookie(res,COOKIE,sign({kind:'user',id:u.id,exp:Date.now()+7*DAY}));res.json({user:clean(u)});}catch(e){res.status(401).json({error:'Đăng nhập Google thất bại'});}});
app.post('/api/logout',(req,res)=>{clearCookie(res,COOKIE);res.json({ok:true});});

app.get('/api/tickets',auth,async(req,res)=>{const rows=await db.sql`SELECT t.id,t.movie_id,t.price,t.created_at,t.watched,m.title,m.genre,m.video FROM tickets t LEFT JOIN movies m ON m.id=t.movie_id WHERE t.user_id=${req.userId} ORDER BY t.created_at DESC`;res.json({tickets:rows.map(r=>({id:r.id,movieId:Number(r.movie_id),price:Number(r.price),created:r.created_at,watched:r.watched,title:r.title,genre:r.genre,video:r.video}))});});
app.post('/api/buy',auth,async(req,res)=>{const movieId=Number(req.body.movieId),client=await db.pool.connect();try{await client.query('BEGIN');const mr=await client.query('SELECT * FROM movies WHERE id=$1 FOR UPDATE',[movieId]);const ur=await client.query('SELECT * FROM users WHERE id=$1 FOR UPDATE',[req.userId]);if(!mr.rows[0])throw Object.assign(new Error('MOVIE'),{status:400});const m=mr.rows[0],u=ur.rows[0];if(Number(u.balance)<Number(m.price))throw Object.assign(new Error('BALANCE'),{status:400});const tid='T'+Date.now().toString(36).toUpperCase()+crypto.randomBytes(3).toString('hex').toUpperCase();await client.query('UPDATE users SET balance=balance-$1 WHERE id=$2',[m.price,u.id]);await client.query('INSERT INTO tickets(id,user_id,movie_id,price) VALUES($1,$2,$3,$4)',[tid,u.id,m.id,m.price]);await client.query('INSERT INTO transactions(user_id,amount,type,ref) VALUES($1,$2,$3,$4)',[u.id,-m.price,'purchase',tid]);await client.query('COMMIT');const nu=(await db.sql`SELECT * FROM users WHERE id=${u.id}`)[0];res.json({user:clean(nu),ticket:{id:tid}});}catch(e){await client.query('ROLLBACK');res.status(e.status||500).json({error:e.message==='BALANCE'?'Không đủ Yoin':'Phim không hợp lệ'});}finally{client.release();}});
app.post('/api/tickets/:id/watch',auth,async(req,res)=>{const r=await db.sql`SELECT * FROM tickets WHERE id=${req.params.id} AND user_id=${req.userId}`;if(!r[0])return res.status(404).json({error:'Không tìm thấy vé'});if(r[0].watched)return res.status(400).json({error:'Vé đã được sử dụng'});await db.sql`UPDATE tickets SET watched=true WHERE id=${r[0].id}`;const m=(await db.sql`SELECT * FROM movies WHERE id=${r[0].movie_id}`)[0];res.json({video:m.video,title:m.title});});

app.post('/api/tasks',auth,upload.single('proof'),async(req,res)=>{if(!req.file)return res.status(400).json({error:'Hãy chọn ảnh bằng chứng'});const pending=await db.sql`SELECT id FROM task_submissions WHERE user_id=${req.userId} AND status='pending'`;if(pending.length)return res.status(400).json({error:'Bạn đã có bằng chứng đang chờ duyệt'});const key='proof/'+crypto.randomUUID();await blobs.set(key,req.file.buffer,{metadata:{contentType:req.file.mimetype,userId:String(req.userId)}});const id='TASK-'+Date.now().toString(36).toUpperCase();await db.sql`INSERT INTO task_submissions(id,user_id,proof_key,status) VALUES(${id},${req.userId},${key},'pending')`;res.json({ok:true});});
app.get('/api/tasks/me',auth,async(req,res)=>{const rows=await db.sql`SELECT id,proof_key,status,reason,created_at FROM task_submissions WHERE user_id=${req.userId} ORDER BY created_at DESC`;res.json({tasks:rows.map(r=>({id:r.id,proof:'/api/proof/'+r.id,status:r.status,reason:r.reason,created:r.created_at}))});});
app.get('/api/proof/:id',async(req,res)=>{const p=verify(req.headers.cookie?.match(new RegExp('(?:^|; )'+COOKIE+'=([^;]+)'))?.[1]),a=verify(req.headers.cookie?.match(new RegExp('(?:^|; )'+ADMIN_COOKIE+'=([^;]+)'))?.[1]);if(!p&&!a)return res.status(401).end();const r=(await db.sql`SELECT proof_key,user_id FROM task_submissions WHERE id=${req.params.id}`)[0];if(!r)return res.status(404).end();if(p&&p.kind==='user'&&Number(p.id)!==Number(r.user_id)&&!a)return res.status(403).end();const entry=await blobs.get(r.proof_key,{type:'arrayBuffer'});if(!entry)return res.status(404).end();const meta=await blobs.getMetadata(r.proof_key);res.setHeader('Content-Type',meta?.metadata?.contentType||'image/jpeg');res.send(Buffer.from(entry));});
app.post('/api/profile',auth,async(req,res)=>{const n=String(req.body.username||'').trim();if(n.length<2)return res.status(400).json({error:'Tên quá ngắn'});await db.sql`UPDATE users SET username=${n} WHERE id=${req.userId}`;res.json({user:clean((await db.sql`SELECT * FROM users WHERE id=${req.userId}`)[0])});});

app.post('/api/admin/login',async(req,res)=>{const email=String(req.body.email||'').trim().toLowerCase(),pass=String(req.body.password||'');let a=(await db.sql`SELECT * FROM admins WHERE email=${email}`)[0];if(!a){const ae=(process.env.ADMIN_EMAIL||'admin@example.com').toLowerCase(),ap=process.env.ADMIN_PASSWORD||'change-this-password';if(email!==ae||pass!==ap)return res.status(401).json({error:'Sai tài khoản QTV'});const h=bcrypt.hashSync(ap,12);a=(await db.sql`INSERT INTO admins(email,password_hash) VALUES(${ae},${h}) ON CONFLICT(email) DO UPDATE SET password_hash=EXCLUDED.password_hash RETURNING *`)[0];}else if(!bcrypt.compareSync(pass,a.password_hash))return res.status(401).json({error:'Sai tài khoản QTV'});setCookie(res,ADMIN_COOKIE,sign({kind:'admin',id:a.id,exp:Date.now()+7*DAY}));res.json({ok:true});});
app.post('/api/admin/logout',(req,res)=>{clearCookie(res,ADMIN_COOKIE);res.json({ok:true});});
app.get('/api/admin/dashboard',admin,async(req,res)=>{const [m,t,r,w]=await Promise.all([db.sql`SELECT COUNT(*) c FROM movies`,db.sql`SELECT COUNT(*) c FROM tickets`,db.sql`SELECT COALESCE(SUM(price),0) c FROM tickets`,db.sql`SELECT COUNT(*) c FROM tickets WHERE watched=true`]);res.json({movies:Number(m[0].c),tickets:Number(t[0].c),revenue:Number(r[0].c),watched:Number(w[0].c)});});
app.get('/api/admin/users',admin,async(req,res)=>{const rows=await db.sql`SELECT id,username,email,balance,invite,created_at FROM users ORDER BY id DESC`;res.json({users:rows.map(x=>({...x,id:Number(x.id),balance:Number(x.balance)}))});});
app.post('/api/admin/users/:id/balance',admin,async(req,res)=>{const d=Math.trunc(Number(req.body.delta)||0);await db.sql`UPDATE users SET balance=GREATEST(0,balance+${d}) WHERE id=${Number(req.params.id)}`;res.json({ok:true});});
app.get('/api/admin/tickets',admin,async(req,res)=>{const rows=await db.sql`SELECT t.id,t.price,t.created_at,t.watched,u.email,m.title FROM tickets t JOIN users u ON u.id=t.user_id JOIN movies m ON m.id=t.movie_id ORDER BY t.created_at DESC`;res.json({tickets:rows.map(x=>({...x,price:Number(x.price)}))});});
app.get('/api/admin/tasks',admin,async(req,res)=>{const rows=await db.sql`SELECT s.id,s.status,s.reason,s.created_at,u.email,u.username FROM task_submissions s JOIN users u ON u.id=s.user_id ORDER BY s.created_at DESC`;res.json({tasks:rows.map(x=>({...x,proof:'/api/proof/'+x.id}))});});
app.post('/api/admin/tasks/:id/review',admin,async(req,res)=>{const s=(await db.sql`SELECT * FROM task_submissions WHERE id=${req.params.id} FOR UPDATE`)[0];if(!s||s.status!=='pending')return res.status(400).json({error:'Không thể duyệt'});const approve=req.body.status==='approved',reason=approve?'':'gian lận trong việc hoàn thành nhiệm vụ trọn đời',delta=approve?30:-5;const client=await db.pool.connect();try{await client.query('BEGIN');await client.query('UPDATE task_submissions SET status=$1,reason=$2,reward_applied=true WHERE id=$3 AND status=\'pending\'',[approve?'approved':'rejected',reason,s.id]);await client.query('UPDATE users SET balance=GREATEST(0,balance+$1) WHERE id=$2',[delta,s.user_id]);await client.query('INSERT INTO transactions(user_id,amount,type,ref) VALUES($1,$2,$3,$4)',[s.user_id,delta,approve?'task_reward':'task_penalty',s.id]);await client.query('COMMIT');res.json({ok:true});}catch(e){await client.query('ROLLBACK');res.status(500).json({error:'Không thể cập nhật task'});}finally{client.release();}});
app.post('/api/admin/movies',admin,upload.fields([{name:'videoFile',maxCount:1},{name:'posterFile',maxCount:1}]),async(req,res)=>{const b=req.body,price=Math.min(35,Math.max(1,Number(b.price)||35));let video=String(b.video||''),poster=String(b.poster||'');if(req.files?.videoFile?.[0]){const f=req.files.videoFile[0];if(f.mimetype!=='video/mp4')return res.status(400).json({error:'Chỉ MP4'});const key='movies/video/'+crypto.randomUUID()+'.mp4';await blobs.set(key,f.buffer,{metadata:{contentType:f.mimetype}});video='/api/media/'+encodeURIComponent(key);}if(req.files?.posterFile?.[0]){const f=req.files.posterFile[0];if(!f.mimetype.startsWith('image/'))return res.status(400).json({error:'Poster phải là ảnh'});const key='movies/poster/'+crypto.randomUUID();await blobs.set(key,f.buffer,{metadata:{contentType:f.mimetype}});poster='/api/media/'+encodeURIComponent(key);}await db.sql`INSERT INTO movies(title,genre,duration,price,poster,video) VALUES(${b.title||'Phim'},${b.genre||'Cinema'},${b.duration||'2h'},${price},${poster},${video})`;res.json({ok:true});});
app.get('/api/media/:key(*)',async(req,res)=>{const key=decodeURIComponent(req.params.key||'');if(!key.startsWith('movies/'))return res.status(403).end();const data=await blobs.get(key,{type:'arrayBuffer'});if(!data)return res.status(404).end();const meta=await blobs.getMetadata(key);res.setHeader('Content-Type',meta?.metadata?.contentType||'application/octet-stream');res.send(Buffer.from(data));});
app.delete('/api/admin/movies/:id',admin,async(req,res)=>{await db.sql`DELETE FROM movies WHERE id=${Number(req.params.id)}`;res.json({ok:true});});
app.patch('/api/admin/movies/:id',admin,async(req,res)=>{const p=Math.min(35,Math.max(1,Number(req.body.price)||1));await db.sql`UPDATE movies SET price=${p} WHERE id=${Number(req.params.id)}`;res.json({ok:true});});

export const handler = serverless(app);
